plugins {
    id 'java'
}

group = 'vn.haohan'
version = '1.0-SNAPSHOT'

base {
    archivesName = 'HaoHanMetallurgy'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly 'vn.haohan:HaoHanDisplayUI:1.0.1'
    compileOnly files('libs/HaoHanItemCore-1.0.0.jar')
    compileOnly 'com.google.code.gson:gson:2.10.1'
    testImplementation 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    testImplementation 'com.google.code.gson:gson:2.10.1'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('processResources') {
    filesMatching(['plugin.yml', 'paper-plugin.yml']) {
        expand(project: [version: project.version])
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
