plugins {
    id 'java'
}

group = 'vn.haohan'
version = '1.0-SNAPSHOT'

base {
    archivesName = 'HaoHanMetallurgy-IgnitePatch'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'fabricmc'
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    compileOnly 'space.vectrix.ignite:ignite-api:1.2.1'
    compileOnly 'net.fabricmc:sponge-mixin:0.17.0+mixin.0.8.7'
    compileOnly 'io.github.llamalad7:mixinextras-common:0.5.3'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += '-proc:none'
}
