name: HaoHanMetallurgy
version: '${project.version}'
main: vn.haohan.metallurgy.HaoHanMetallurgy
api-version: '1.21'
description: Data-driven metallurgy system for HaoHan SMP
authors: [ HaoHanSMP ]
website: https://haohansmp.dev
depend: [ HaoHanDisplayUI, HaoHanItemCore ]

commands:
  metallurgy:
    description: HaoHan Metallurgy main command
    usage: /metallurgy <info|reload|debug|list|give|menu|language>
    permission: haohansmp.metallurgy.admin
    aliases: [ met, forge ]

permissions:
  haohansmp.metallurgy.admin:
    description: Access to all /metallurgy admin commands
    default: op
  haohansmp.metallurgy.use:
    description: Can interact with metallurgy machines
    default: true
